import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]


class PublicDocsTests(unittest.TestCase):
    def test_readme_routes_readers_to_the_public_edition(self) -> None:
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("https://seo.suedeai.ai/book", readme)
        self.assertIn("https://jasoncolapietro.github.io/suede-geo-book/", readme)
        self.assertIn("SEO and GEO", readme)
        self.assertIn("The Screenshot", readme)
        self.assertIn("python3 pages/build.py --output _site --pandoc pandoc", readme)
        self.assertNotIn("AI-generated", readme)
        self.assertNotIn("generated by AI", readme.lower())

    def test_citation_file_identifies_the_book(self) -> None:
        citation = (ROOT / "CITATION.cff").read_text(encoding="utf-8")
        self.assertIn("cff-version: 1.2.0", citation)
        self.assertIn("title: 'The Screenshot'", citation)
        self.assertIn("family-names: 'Colapietro'", citation)
        self.assertIn("version: 1.0.0", citation)
        self.assertIn("date-released: '2026-08-28'", citation)
        self.assertIn("url: 'https://seo.suedeai.ai/book'", citation)

    def test_pages_workflow_builds_audits_and_deploys(self) -> None:
        workflow = (ROOT / ".github/workflows/pages.yml").read_text(encoding="utf-8")
        for required in (
            "actions/checkout@v6",
            "actions/setup-python@v6",
            "actions/configure-pages@v5",
            "actions/upload-pages-artifact@v5",
            "actions/deploy-pages@v5",
            "python3 pages/build.py --output _site --pandoc pandoc",
            "python3 tools/audit_public_copy.py _site",
            "python3 tools/audit_public_release.py",
            "pages: write",
            "id-token: write",
        ):
            self.assertIn(required, workflow)
        self.assertIn("environment:", workflow)
        self.assertIn("github-pages", workflow)


if __name__ == "__main__":
    unittest.main()
