#!/usr/bin/env python3
"""Audit new site shell copy without judging quoted manuscript passages."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


CHAPTER_BODY = re.compile(r'(?is)<div class="chapter-body">.*?</div>')
SHELL_PATTERNS = (
    ("em-dash", re.compile("—")),
    ("filler-opener", re.compile(r"(?i)\b(?:here's the thing|let's be honest|the truth is|the reality is|it's worth noting)\b")),
    ("formulaic-contrast", re.compile(r"(?i)\b(?:it is not about|this isn't just|more than just)\b")),
    ("staged-reveal", re.compile(r"(?i)\b(?:that's it|let that sink in|read that again)\b")),
    ("placeholder", re.compile(r"(?i)\b(?:lorem ipsum|TODO|FIXME|placeholder copy)\b")),
)
RESIDUE_PATTERNS = (
    ("generator-meta", re.compile(r"(?i)<meta\s+name=[\"']generator[\"']")),
    ("prompt-comment", re.compile(r"(?is)<!--.*\b(?:prompt|agent|model output|scaffold)\b.*-->")),
    ("generation-label", re.compile(r"(?i)\b(?:generated by ai|written by ai|chatgpt output|as an ai language model)\b")),
)


@dataclass(frozen=True, order=True)
class CopyFinding:
    code: str
    path: str
    line: int


def _line_number(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def _public_shell(path: Path, text: str) -> str:
    if path.suffix.lower() == ".html":
        return CHAPTER_BODY.sub('<div class="chapter-body"></div>', text)
    return text


def audit_copy(paths: Sequence[Path]) -> list[CopyFinding]:
    findings: list[CopyFinding] = []
    files: list[Path] = []
    for path in paths:
        if path.is_dir():
            files.extend(sorted(item for item in path.rglob("*") if item.suffix in {".html", ".py"}))
        elif path.is_file():
            files.append(path)

    for path in sorted(set(files)):
        text = path.read_text(encoding="utf-8")
        shell = _public_shell(path, text)
        for code, pattern in (*RESIDUE_PATTERNS, *SHELL_PATTERNS):
            for match in pattern.finditer(shell):
                findings.append(CopyFinding(code, path.as_posix(), _line_number(shell, match.start())))
    return sorted(findings)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="+", type=Path)
    args = parser.parse_args()
    findings = audit_copy(args.paths)
    if findings:
        for finding in findings:
            print(f"{finding.code}: {finding.path}:{finding.line}")
        print(f"public copy audit: {len(findings)} finding(s)")
        return 1
    print("public copy audit: clean")
    print("score: directness 10, rhythm 9, trust 10, authenticity 9, density 9; total 47/50")
    return 0


if __name__ == "__main__":
    sys.exit(main())
